spring:
  application:
    name: microservicecloud-dept-config-client


#spring:
#  profiles:
#    active:
#    - dev
#
#---
#spring:
#  profiles: dev #开发环境
#  application:
#    name: microservice dev
#server:
#  port: 8081
#---
#server:
#  port: 8082
#spring:
#  profiles: test #测试环境
#  application:
#    name: microservice test
