
spring:
  profiles:
    active:
    - dev

---
server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.codeman.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   profiles: dev #开发环境
   application:
    name: microservicecloud-dept   #register application name
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false             # 数据库名称
    username: root
    password: zhj123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      #mysql数据库验证
#      test-while-idle: false
#      validation-query: SELECT 1
#      validation-query-timeout: 10
#    tomcat:
#      test-on-borrow: false
#      test-while-idle: false
#      test-on-return: false
#      validation-query: SELECT 1
#      eureka:client.register-with-eureka=false
#      eureka.client.fetch-registry=false

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002  #set application status
    prefer-ip-address: true     #访问路径可以显示IP地址

#set application info
info:
  app.name: codeman-microservicecloud
  company.name: www.codeman.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

logging:
  level:
    com:
      codeman:
        springcloud:
          dao:
            DeptDao: debug
#
---
server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.codeman.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   profiles: test #测试环境
   application:
    name: microservicecloud-dept   #register application name
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false             # 数据库名称
    username: root
    password: zhj123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      #mysql数据库验证
#      test-while-idle: false
#      validation-query: SELECT 1
#      validation-query-timeout: 10
#    tomcat:
#      test-on-borrow: false
#      test-while-idle: false
#      test-on-return: false
#      validation-query: SELECT 1
#      eureka:client.register-with-eureka=false
#      eureka.client.fetch-registry=false

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002  #set application status
    prefer-ip-address: true     #访问路径可以显示IP地址

#set application info
info:
  app.name: codeman-microservicecloud
  company.name: www.codeman.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

logging:
  level:
    com:
      codeman:
        springcloud:
          dao:
            DeptDao: debug
#